version: '3.4'

services:
  kleskaproject.api:
    image: ${DOCKER_REGISTRY-}kleskaprojectapi
    build:
      context: .
      dockerfile: KleskaProject.API/Dockerfile
    ports:
      - "8080:8080" # HTTP
      - "8081:8081" # HTTPS